module.exports = {
  apps: [
    {
      name: 'command-center',
      script: 'dist/server/server/index.js',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        COMMAND_CENTER_PORT: '3142',
      },
      exp_backoff_restart_delay: 1000,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'agent-research',
      script: 'node_modules/.bin/tsx',
      args: 'agents/research/index.ts',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        RESEARCH_AGENT_PORT: '3143',
      },
      exp_backoff_restart_delay: 1000,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'agent-coding',
      script: 'node_modules/.bin/tsx',
      args: 'agents/coding/index.ts',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        CODING_AGENT_PORT: '3144',
      },
      exp_backoff_restart_delay: 1000,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'agent-content',
      script: 'node_modules/.bin/tsx',
      args: 'agents/content/index.ts',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        CONTENT_AGENT_PORT: '3145',
      },
      exp_backoff_restart_delay: 1000,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'agent-data',
      script: 'node_modules/.bin/tsx',
      args: 'agents/data/index.ts',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        DATA_AGENT_PORT: '3146',
      },
      exp_backoff_restart_delay: 1000,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'agent-kup',
      script: 'node_modules/.bin/tsx',
      args: 'agents/kup/index.ts',
      cwd: __dirname,
      env: {
        NODE_ENV: 'production',
        KUP_AGENT_PORT: '3147',
      },
      exp_backoff_restart_delay: 1000,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};
