/**
 * A2A (Agent-to-Agent) Protocol Types
 *
 * Defines the contract between Data (orchestrator) and all specialist agents.
 * Every A2A agent must:
 *   1. Serve GET /.well-known/agent.json → A2AAgentCard
 *   2. Accept POST /task → A2ATaskResponse (creates task)
 *   3. Serve GET /task/:id → A2ATaskStatus (poll for results)
 */

// ── Agent Card ───────────────────────────────────────────────────────
// Served at GET /.well-known/agent.json — describes what the agent can do

export interface A2AAgentCard {
  /** Unique agent identifier */
  id: string;
  /** Human-readable agent name */
  name: string;
  /** What this agent does */
  description: string;
  /** Capability tags for routing (e.g., 'research', 'coding', 'content') */
  skills: string[];
  /** Agent type: 'named' agents have custom logic, 'stock' run generic shell */
  type: 'named' | 'stock';
  /** A2A protocol version */
  protocol_version: '0.1';
  /** Base URL for this agent (e.g., http://localhost:3143) */
  endpoint: string;
  /** Task input schema hints (informal, for routing decisions) */
  accepts: string[];
  /** Task output format hints */
  produces: string[];
}

// ── Task Lifecycle ───────────────────────────────────────────────────

export type A2ATaskState = 'queued' | 'running' | 'completed' | 'failed' | 'cancelled';

/** POST /task — request body */
export interface A2ATaskRequest {
  /** Unique task ID (generated by sender) */
  id: string;
  /** The goal/prompt for the agent */
  goal: string;
  /** Additional context (memory, prior results, constraints) */
  context?: string;
  /** Optional skill hint. If provided, the agent may select a skill-specific model (R2.4). */
  skill?: string;
  /** Who sent this task */
  sender: {
    id: string;
    name: string;
  };
  /** Timeout in ms (agent should respect this) */
  timeout_ms?: number;
}

/** POST /task — response body (immediate acknowledgment) */
export interface A2ATaskResponse {
  /** Echoed task ID */
  task_id: string;
  /** Initial state (should be 'queued' or 'running') */
  state: A2ATaskState;
  /** Estimated completion time in seconds (optional) */
  estimated_seconds?: number;
}

/** GET /task/:id — poll response */
export interface A2ATaskStatus {
  task_id: string;
  state: A2ATaskState;
  /** Progress description (human-readable) */
  progress?: string;
  /** Result text (populated when state === 'completed') */
  result?: string;
  /** Error message (populated when state === 'failed') */
  error?: string;
  /** Duration in ms (populated when terminal state) */
  duration_ms?: number;
  /** Structured logs from execution */
  logs?: A2ATaskLog[];
}

export interface A2ATaskLog {
  timestamp: number;
  level: 'info' | 'progress' | 'error';
  message: string;
}

// ── Discovery ────────────────────────────────────────────────────────
// Data uses these to find and register agents

export interface A2AAgentRegistration {
  /** Agent card URL (e.g., http://localhost:3143/.well-known/agent.json) */
  card_url: string;
  /** Last time the card was fetched */
  last_fetched: number;
  /** Whether the agent is reachable */
  reachable: boolean;
}
